export const departments = [
    {
        id: 0,
        name: "Fruit Dept.",
        icon: "🍎",
        level: 1, 
        baseCost: 5,
        baseIncome: 1,
        isUnlocked: true,
        minUnlockBalance: 0,
        requiredArea: 1,
        milestones: [
            { lvl: 0, title: "Inedible Peels", desc: "Full of nutrients... doctors say." },
            { lvl: 10, title: "Rotten Fruit", desc: "Biologically questionable, but better than nothing." },
            { lvl: 20, title: "Overripe Fruit", desc: "A bit mushy but you can still consider it fruit." },
            { lvl: 30, title: "Ripe Fruit", desc: "Perfectly timed. The bare minimum of competence." },
            { lvl: 40, title: "Fresh Fruit", desc: "Crisp, juicy, and finally something customers trust." },
            { lvl: 50, title: "More Variety", desc: "Why sell one fruit when you can sell twelve and confuse everyone?" },
            { lvl: 60, title: "Sweet Fruit", desc: "Naturally sweeter fruit that keeps customers coming back for more." },
            { lvl: 70, title: "Exotic Fruit", desc: "Rare imports with names nobody can pronounce, but we sell it anyway." },
            { lvl: 80, title: "Big Fruit", desc: "Same fruit. Way bigger. Size matters." },
            { lvl: 90, title: "Seedless Fruit", desc: "All the flavor, none of the inconvenience." },
            { lvl: 100, title: "Skinless Fruit", desc: "Ready-to-eat fruit engineered for maximum laziness." },
            { lvl: 125, title: "Pre-cut Fruit", desc: "Sliced, diced, and suspiciously expensive." },
            { lvl: 150, title: "Eternity Fruit", desc: "It never spoils. It never ages. It watches." },
            { lvl: 175, title: "Instant Fruit", desc: "Planted and harvested at the same time. Agriculture optimized to absurdity." },
            { lvl: 200, title: "Fruity!", desc: "FRUIT! FRUIT! FRUIT!" },
            { lvl: 250, title: "Golden Apple", desc: "A legendary fruit worth more than entire orchards." },
            { lvl: 300, title: "The Giant Peach", desc: "We stole this from James. Limited quantity." },
            { lvl: 350, title: "Ancient Fruit", desc: "Cultivated using forgotten methods from a civilization that knew too much." },
            { lvl: 400, title: "Alien Fruit", desc: "Not from this planet. Probably safe. Probably." },
            { lvl: 500, title: "Self-Duplicating Fruit", desc: "Every harvest creates more fruit than planted. Economy is broken. (we still charge full price)" },
            { lvl: 600, title: "Celeste Strawberry", desc: "It makes a cool sound when you hold it." },
            { lvl: 700, title: "Stardrop", desc: "Increases energy by quite a bit." },
            { lvl: 800, title: "Forbidden Fruit", desc: "The fruit of knowledge." },
            { lvl: 900, title: "Devil Fruits", desc: "Grants immense, varied powers to consumers but takes away their ability to swim." },
            { lvl: 1000, title: "Peach of Immortality", desc: "From the Monkey King himself." }
        ]
    },
    {
        id: 1,
        name: "Vegetable Dept.",
        icon: "🥬",
        level: 0,
        baseCost: 10,
        baseIncome: 5,
        isUnlocked: false,
        minUnlockBalance: 50,
        requiredArea: 1,
        milestones: [
            { lvl: 0, title: "Dirt", desc: "Not technically vegetables, but we're starting somewhere." },
            { lvl: 10, title: "Water", desc: "Hydration unlocked. Growth is now theoretically possible." },
            { lvl: 20, title: "Roots", desc: "Buried deep underground, just like our profits used to be." },
            { lvl: 30, title: "Just Celery", desc: "Crunchy." },
            { lvl: 40, title: "Green Veggies", desc: "Leafy, nutritious, and universally ignored by children." },
            { lvl: 50, title: "More Veggies!", desc: "We added more vegetables. No one asked which ones." },
            { lvl: 60, title: "Tomatoes!", desc: "Is it a fruit? Is it a vegetable? We sell it anyway." },
            { lvl: 70, title: "Potatoes!", desc: "The backbone of civilization in vegetable form." },
            { lvl: 80, title: "Garlic", desc: "Repels vampires and coworkers alike." },
            { lvl: 90, title: "Carolina Reaper", desc: "Extremely spicy. Waiver required before purchase." },
            { lvl: 100, title: "Mushrooms", desc: "Some are delicious. Some are suspicious. All sell well." },
            { lvl: 125, title: "Dental Veggies", desc: "So crunchy dentists have started sponsoring us." },
            { lvl: 150, title: "Ultra-healthy", desc: "Doctors approve. Taste is optional." },
            { lvl: 175, title: "Medicinal Veggies", desc: "Prescribed by professionals who really love vegetables." },
            { lvl: 200, title: "Chocolate Veggies", desc: "Legally vegetables. Morally dessert." },
            { lvl: 250, title: "Edible Tree", desc: "Why harvest vegetables when the whole tree works?" },
            { lvl: 300, title: "Happy Onions", desc: "Cutting these won't make you cry. Emotionally supportive produce." },
            { lvl: 350, title: "Energy Eggplants", desc: "One bite and suddenly you can do chores." },
            { lvl: 400, title: "Time-Twisting Turnips", desc: "Lets you revisit moments from your past. Mostly regret." },
            { lvl: 500, title: "Rainbow Radishes", desc: "They change color as you slice them. Science refuses to explain." },
            { lvl: 600, title: "Cool Cucumbers", desc: "Always chilled. Somehow judgmental." },
            { lvl: 700, title: "Gillyweed", desc: "Eat this and breathing underwater becomes a lifestyle choice." },
            { lvl: 800, title: "Giant Beanstalk", desc: "Grows beyond the clouds. We charge extra for altitude." },
            { lvl: 900, title: "Popeye’s Spinach", desc: "Instant strength. Forearms not included." },
            { lvl: 1000, title: "Cactus Juice", desc: "A hallucinogenic drink. Exchanged a boomerang for this from a certain person." }
        ]
    },
    {
        id: 2,
        name: "Bakery Dept.",
        icon: "🥐",
        level: 0,
        baseCost: 100,
        baseIncome: 10,
        isUnlocked: false,
        minUnlockBalance: 500,
        requiredArea: 1,
        milestones: [
            { lvl: 0, title: "Dough", desc: "Unbaked potential. Fum to play with." },
            { lvl: 10, title: "Stale White Bread", desc: "Barely edible, but technically bread." },
            { lvl: 20, title: "White Bread", desc: "Soft, simple, and nutritionally mysterious." },
            { lvl: 30, title: "Whole Wheat Bread", desc: "Healthier. Slightly more respected." },
            { lvl: 40, title: "Seed Bread", desc: "Now with visible proof of effort." },
            { lvl: 50, title: "Multigrain Bread", desc: "Many, many grains. Not sure where they're all from though." },
            { lvl: 60, title: "Low-carb Bread", desc: "Bread that apologizes for being bread. Good for dieting though." },
            { lvl: 70, title: "Bagels", desc: "Dense, circular, and dangerously filling." },
            { lvl: 80, title: "Baguettes and Croissants", desc: "Oui Oui Oui." },
            { lvl: 90, title: "Sourdough Bread", desc: "Naturally fermented and mildly judgmental." },
            { lvl: 100, title: "Rustic Bread", desc: "Looks handmade. Costs extra because of it." },
            { lvl: 125, title: "Pretzel Bread", desc: "Salty, chewy, and immediately addictive." },
            { lvl: 150, title: "Brioche Bread", desc: "So rich it qualifies as a luxury good." },
            { lvl: 175, title: "Garlic Bread", desc: "Objectively the best form of bread." },
            { lvl: 200, title: "Fruit Bread", desc: "Is it dessert? Is it breakfast? Is it amazing? Yes." },
            { lvl: 250, title: "Cheese Bread", desc: "Bread reinforced with melted motivation." },
            { lvl: 300, title: "Crunchy Bread", desc: "Not the look, not the smell, but the SOUND!" },
            { lvl: 350, title: "Buttery Bread", desc: "Bread soaked in pure indulgence." },
            { lvl: 400, title: "Hot Bread", desc: "Fresh out of the oven. Good with honey butter." },
            { lvl: 500, title: "Non-perishable Bread", desc: "Will outlast civilizations. Still soft." },
            { lvl: 600, title: "Gladiator Bread", desc: "Baked for warriors. Eaten by champions." },
            { lvl: 700, title: "Insta-bread", desc: "Baked instantly. Physics quietly resigns." },
            { lvl: 800, title: "Lembas Bread", desc: "One bite sustains a person for an entire journey." },
            { lvl: 900, title: "Gingerbread", desc: "He might come to life. Whatever, he's delicious." },
            { lvl: 1000, title: "The Breadestry", desc: "An entire family tree of bread. It grows exponentially." }
        ]
    },
    {
        id: 3,
        name: "Confectionary Dept.",
        icon: "🎂",
        level: 0,
        baseCost: 300,
        baseIncome: 25,
        isUnlocked: false,
        minUnlockBalance: 1500,
        requiredArea: 1,
        milestones: [
            { lvl: 0, title: "Tasteless Sprinkles", desc: "Purely decorative. Emotionally disappointing." },
            { lvl: 10, title: "Sprinkles", desc: "Now with actual flavor. Barely." },
            { lvl: 20, title: "Frosting", desc: "Sweet, smooth, and doing most of the work." },
            { lvl: 30, title: "Cupcakes", desc: "Tiny cakes with big confidence." },
            { lvl: 40, title: "Cakes", desc: "The backbone of all celebrations." },
            { lvl: 50, title: "Croissants", desc: "Flaky, buttery, and legally fancy." },
            { lvl: 60, title: "Chocolate Lava Cake", desc: "Molten on the inside. Structurally unstable." },
            { lvl: 70, title: "Donuts", desc: "Fried perfection with a suspicious hole." },
            { lvl: 80, title: "Cookies", desc: "Crunchy, chewy, or both. Arguments ensue." },
            { lvl: 90, title: "Pie", desc: "Basically fruit wearing sugar. So delicious though." },
            { lvl: 100, title: "Baklava", desc: "Layers of pastry, honey, and financial success." },
            { lvl: 125, title: "Mooncake", desc: "Dense, symbolic, and surprisingly powerful." },
            { lvl: 150, title: "Ice Cream", desc: "Cold happiness. Melts under pressure." },
            { lvl: 175, title: "Creme Brulee", desc: "Crack the top. A euphoric sound." },
            { lvl: 200, title: "Wonka Bar", desc: "Whippe-Scrumptious Fudgmallow Delight!" },
            { lvl: 250, title: "Chocolate Frog", desc: "Chocolatey. Attempts escape." },
            { lvl: 300, title: "Flavor Explosion", desc: "So much flavor it borders on dangerous." },
            { lvl: 350, title: "Healthy", desc: "Dessert that claims to be good for you." },
            { lvl: 400, title: "Energy (no sugar crash)", desc: "Infinite energy. Zero consequences. Somehow." },
            { lvl: 500, title: "Candy Room", desc: "An entire room made of sweets. Structural integrity questionable." },
            { lvl: 600, title: "Scooby Snacks", desc: "Who's a good boy?" },
            { lvl: 700, title: "Chocolate River", desc: "Enough for many lifetimes. Maintenance is expensive." },
            { lvl: 800, title: "Bruce's Cake", desc: "The cake was fully 18 inches in diameter." },
            { lvl: 900, title: "Speedrun Sugar", desc: "Take this to break world records." },
            { lvl: 1000, title: "Wondertart", desc: "The Delicious Last Course." }
        ]
    },
    {
        id: 4,
        name: "Meat Dept.",
        icon: "🥩",
        level: 0,
        baseCost: 700,
        baseIncome: 50,
        isUnlocked: false,
        minUnlockBalance: 3500,
        requiredArea: 1,
        milestones: [
            { lvl: 0, title: "Maybe Meat?", desc: "It resembles meat. No further questions allowed." },
            { lvl: 10, title: "Raw", desc: "IT'S RAW!" },
            { lvl: 20, title: "Tendons", desc: "Chewy, not very tasty." },
            { lvl: 30, title: "Tongue", desc: "Ironically tastes better than it sounds." },
            { lvl: 40, title: "Shoe Meat", desc: "Texture suspiciously familiar." },
            { lvl: 50, title: "Hotdog Meat", desc: "No one knows what’s in it. Everyone eats it anyway. Very cheap at a certain corporation." },
            { lvl: 60, title: "Meat", desc: "Just meat. Honest. Reliable. Packed with amino acids." },
            { lvl: 70, title: "Fresh Meat", desc: "Recently acquired and won't spoil. You can also use it to insult newcomers." },
            { lvl: 80, title: "Cured Meat", desc: "Preserved with time, salt, and patience." },
            { lvl: 90, title: "Cold Cuts", desc: "Thinly sliced efficiency. Works well on charcuterie boards." },
            { lvl: 100, title: "Baaaaccoooon", desc: "The universal motivator." },
            { lvl: 125, title: "Beef Jerky", desc: "Meat that survived the apocalypse. A great snack." },
            { lvl: 150, title: "High Protein Meat", desc: "Optimized for gains. Still just as tasty." },
            { lvl: 175, title: "Marbled Meat", desc: "Fat distribution perfected." },
            { lvl: 200, title: "A5 Wagyu", desc: "So tender and fatty it questions your worth." },
            { lvl: 250, title: "Lab Meat", desc: "Grown without animals. Or patience. Try it out!" },
            { lvl: 300, title: "Tofu Meat", desc: "Meat in spirit. For the vegans." },
            { lvl: 350, title: "T-Rex Meat", desc: "Extinct flavor. Not really sure how we acquired this." },
            { lvl: 400, title: "Werewolf Meat", desc: "Extremely lean and slightly cursed." },
            { lvl: 500, title: "Unicorn Meat", desc: "Incredibly magical and incredibly profitable. THey're difficult to catch though." },
            { lvl: 600, title: "Dragon Meat", desc: "Still warm. Spicy by default." },
            { lvl: 700, title: "Godzilla Meat", desc: "Radioactive flavor profile. Massive portions that could feed cities." },
            { lvl: 800, title: "Fried Phoenix Wings", desc: "Regenerates after frying. Infinite supply. Very hot." },
            { lvl: 900, title: "Martian Meat", desc: "Not from Earth. Not bad with seasoning." },
            { lvl: 1000, title: "Galaxy Meat", desc: "Harvested from something far, far away." }
        ]
    },
    {
        id: 5,
        name: "Seafood Dept.",
        icon: "🐟",
        level: 0,
        baseCost: 1400,
        baseIncome: 100,
        isUnlocked: false,
        minUnlockBalance: 7000,
        requiredArea: 2,
        milestones: [
            { lvl: 0, title: "Uh…", desc: "We don't really know what this is..." },
            { lvl: 10, title: "Pond Scum", desc: "You are lower than this. You have a problem with that?" },
            { lvl: 20, title: "Sea Bug", desc: "More legs than expected. Kinda crunchy." },
            { lvl: 30, title: "Seaweed", desc: "Not fish, but definitely wet. Good on salad." },
            { lvl: 40, title: "Smelly Fish", desc: "Freshness is a suggestion. This also smells like ur mom's p*****" },
            { lvl: 50, title: "Canned Fish", desc: "Preserved indefinitely. Aroma included. Usually salty." },
            { lvl: 60, title: "Fresh Fish", desc: "Caught from a river less than 15 minutes ago, trust us!" },
            { lvl: 70, title: "Tuna Fish", desc: "Big, fast, and extremely profitable." },
            { lvl: 80, title: "Salmon", desc: "Swims upstream for flavor reasons. We think." },
            { lvl: 90, title: "Sushi", desc: "Raw confidence on rice. Very expensive but so worth it." },
            { lvl: 100, title: "Oysters", desc: "Slimy luxury with attitude." },
            { lvl: 125, title: "Shrimp", desc: "Small, pink, and everywhere. They can also fry rice" },
            { lvl: 150, title: "Crab", desc: "They rave to some funky music." },
            { lvl: 175, title: "Lobsters", desc: "Fancy tanks included. Very good with butter" },
            { lvl: 200, title: "Octopus", desc: "Too intelligent for comfort. Has three hearts but isn't too friendly," },
            { lvl: 250, title: "Jellyfish", desc: "Mostly water. Surprisingly dangerous. We really don't know how it tastes." },
            { lvl: 300, title: "Blobfish", desc: "Looks worse outside its comfort zone." },
            { lvl: 350, title: "Caviar", desc: "Tiny eggs with massive price tag." },
            { lvl: 400, title: "Shark", desc: "All teeth. No mercy. In a lot of movies." },
            { lvl: 500, title: "Megalodon Fin", desc: "Extinct...allegedly." },
            { lvl: 600, title: "Mermaid Tail", desc: "Ethically questionable. Magically tender. We sell their other product at the dairy department..." },
            { lvl: 700, title: "Charybdis Eyes", desc: "Staring back at you feels unwise." },
            { lvl: 800, title: "Davy Jones’s Beard", desc: "Salty, cursed, and nautical. Had to go through a lot of pirates for this." },
            { lvl: 900, title: "Kraken", desc: "Requires multiple boats to harvest. We lost three of them." },
            { lvl: 1000, title: "Tail of Poseidon", desc: "We challenged gods, and, of course, we won." },
            { lvl: 1200, title: "Fish with Legs", desc: "From a different universe. Walked here willingly. Pretty much the same flavor." }
        ]
    },
    {
        id: 6,
        name: "Dairy Dept.",
        icon: "🧀",
        level: 0,
        baseCost: 3000,
        baseIncome: 160,
        isUnlocked: false,
        minUnlockBalance: 15000,
        requiredArea: 2,
        milestones: [
            { lvl: 0, title: "Playground Cheese", desc: "Found near the slide. Questionable origin." },
            { lvl: 10, title: "Moldy Cheese", desc: "We waited too long. Still selling it for a slightly decreased price." },
            { lvl: 20, title: "Blue Cheese", desc: "Mold, but on purpose this time." },
            { lvl: 30, title: "Cheese", desc: "Just cheese. Reliable. Honest." },
            { lvl: 40, title: "Sliced Cheese", desc: "Perfectly square. Emotionally processed." },
            { lvl: 50, title: "Shredded Cheese", desc: "Same cheese. More surface area." },
            { lvl: 60, title: "String Cheese", desc: "Playable food." },
            { lvl: 70, title: "Nacho Cheese", desc: "Not your cheese. Still yours." },
            { lvl: 80, title: "Greek Yogurt", desc: "Thick, powerful, and quietly judging you." },
            { lvl: 90, title: "American Yogurt", desc: "Sweeter. Less judgmental." },
            { lvl: 100, title: "Butter", desc: "Makes everything better instantly." },
            { lvl: 125, title: "Herb Butter", desc: "Butter that went to culinary school." },
            { lvl: 150, title: "Milk", desc: "Classic. Refreshing. Mysteriously necessary." },
            { lvl: 175, title: "Chocolate Milk", desc: "Milk but fun." },
            { lvl: 200, title: "SO MANY MILKS", desc: "Almond. Oat. Soy. Something else." },
            { lvl: 250, title: "Creamer", desc: "Coffee's best friend." },
            { lvl: 300, title: "Gelato", desc: "Ice cream with confidence." },
            { lvl: 350, title: "Sour Cream", desc: "Tangy support character." },
            { lvl: 400, title: "Crème Fraîche", desc: "Sour cream wearing a tuxedo." },
            { lvl: 500, title: "Galactic Gouda", desc: "Aged in zero gravity." },
            { lvl: 600, title: "Aged Cheddar", desc: "Eating this cheese slows aging. The cheese itself is ancient." },
            { lvl: 700, title: "Leprechaun’s Lactose-Free Milk", desc: "No lactose intolerance. Slightly mischievous aftertaste." },
            { lvl: 800, title: "Mermaid Milk", desc: "Don’t ask how we got it. Just drink it bro. Trust." },
            { lvl: 900, title: "Pac-man Cheese", desc: "Perfectly circular. May move... or try to eat you." },
            { lvl: 1000, title: "Moon Cheese", desc: "Collected during the full moon. Requires NASA." }
        ]
    },
    {
        id: 7,
        name: "Beverage Dept.",
        icon: "🥤",
        level: 0,
        baseCost: 30000,
        baseIncome: 250,
        isUnlocked: false,
        minUnlockBalance: 30000,
        requiredArea: 3,
        milestones: [
            { lvl: 0, title: "From Below (sewer)", desc: "Sourced from somewhere no one wants to talk about. The taste builds character. Mostly negative character." },
            { lvl: 10, title: "Stale Water", desc: "It hydrates, but only reluctantly. Has the aftertaste of forgotten bottles." },
            { lvl: 20, title: "Water", desc: "Clean, clear, and historically one of humanity’s greatest inventions. Sales spike immediately." },
            { lvl: 30, title: "Sparkling Water", desc: "Water, but it bites back. Customers pretend to like it." },
            { lvl: 40, title: "Lightly Flavored Water", desc: "A hint of fruit essence. The fruit was never present." },
            { lvl: 50, title: "Flavored Water", desc: "Now you can actually identify the flavor if you focus hard enough." },
            { lvl: 60, title: "Smart Water", desc: "Claims to enhance performance. Refuses to explain how." },
            { lvl: 70, title: "Fruit Juice", desc: "Several fruits sacrificed for one glass. Pulp debates intensify." },
            { lvl: 80, title: "Soda", desc: "Carbonated joy with absolutely no long-term consequences (allegedly)." },
            { lvl: 90, title: "Beer", desc: "Liquid confidence unlocked. Productivity stats drop mysteriously." },
            { lvl: 100, title: "Wine", desc: "Aged carefully to taste expensive. Improves opinions." },
            { lvl: 125, title: "Tequila", desc: "Activates bad decisions instantly. Regret follows shortly after." },
            { lvl: 150, title: "Champagne", desc: "Everything feels like an achievement when this pops." },
            { lvl: 175, title: "Protein Shakes", desc: "Tastes like effort and gym lighting. Gains guaranteed." },
            { lvl: 200, title: "Butterbeer", desc: "Foamy, sweet, and suspiciously comforting. No age verification required." },
            { lvl: 250, title: "Chug Jug", desc: "Restores vitality at an alarming rate. Best consumed mid-crisis." },
            { lvl: 300, title: "Fire Resistance Potion", desc: "After drinking this, flames become more of a suggestion. OSHA has concerns." },
            { lvl: 350, title: "3 Course Meal", desc: "An appetizer, entrée, and dessert condensed into liquid form. Chewing is optional." },
            { lvl: 400, title: "1000 Year Old Fermented", desc: "Aged longer than most civilizations. The flavor is… assertive." },
            { lvl: 500, title: "Alien Juice", desc: "Not designed for human biology. Still wildly popular." },
            { lvl: 600, title: "Multicolor Urine", desc: "Science refuses to comment. Customers also stop asking." },
            { lvl: 700, title: "Quencher", desc: "Eliminates thirst on a metaphysical level. Side effect: enlightenment." },
            { lvl: 800, title: "Love Potion", desc: "Strong emotional effects. Results expire suddenly." },
            { lvl: 900, title: "Luck Potion", desc: "Subtly bends probability in your favor. Dice rolls feel personal now." },
            { lvl: 1000, title: "Divine Drink", desc: "Consumed by gods, mortals, and anyone with enough money. Reality feels slightly thinner afterward." }
        ]
    },
    {
        id: 8,
        name: "Clothing Dept.",
        icon: "👚",
        level: 0,
        baseCost: 60000,
        baseIncome: 500,
        isUnlocked: false,
        minUnlockBalance: 60000,
        requiredArea: 3,
        milestones: [
            { lvl: 0, title: "Toe Warmers", desc: "Barely qualifies as clothing. Keeps exactly two toes warm and builds false confidence." },
            { lvl: 10, title: "Short Socks", desc: "Technically functional. Disappears inside shoes like it was never there." },
            { lvl: 20, title: "Regular Socks", desc: "Reliable, symmetrical, and occasionally mismatched." },
            { lvl: 30, title: "Sneakers", desc: "Suddenly, walking feels intentional. Sprinting feels unlocked." },
            { lvl: 40, title: "Shorts", desc: "Freedom for the legs. Weather permitting." },
            { lvl: 50, title: "Pants", desc: "Full leg coverage achieved. Society approves." },
            { lvl: 60, title: "T-Shirts", desc: "Simple, versatile, and capable of holding opinions via text." },
            { lvl: 70, title: "Brand Shirts", desc: "Costs more. Does the same thing. Confidence increases anyway." },
            { lvl: 80, title: "Jackets", desc: "Style and warmth combined into one socially acceptable layer." },
            { lvl: 90, title: "Gloves", desc: "Keeps hands warm—or fingerprints nonexistent. Use responsibly." },
            { lvl: 100, title: "Swimwear", desc: "Clothing designed specifically to get wet. Fashion logic collapses." },
            { lvl: 125, title: "Caps", desc: "Protects from sun, bad hair days, and unwanted eye contact." },
            { lvl: 150, title: "Top Hat", desc: "Instantly raises charisma. Also attracts monocles." },
            { lvl: 175, title: "Suits", desc: "Wearing this makes people assume you know what you’re doing." },
            { lvl: 200, title: "Designer Shoes", desc: "Uncomfortable, expensive, and inexplicably powerful." },
            { lvl: 250, title: "Dresses", desc: "Elegant, flowing, and capable of commanding entire rooms." },
            { lvl: 300, title: "Spy Suit", desc: "Optimized for stealth, gadgets, and dramatic hallway fights." },
            { lvl: 350, title: "Knight Armor", desc: "Heavy, loud, and extremely confident against swords." },
            { lvl: 400, title: "Costumes", desc: "Become anyone. Legally distinct from copyright." },
            { lvl: 500, title: "Invisible Suit", desc: "You’re still there. No one can prove it." },
            { lvl: 600, title: "Bulletproof Suit", desc: "Stops bullets while maintaining a professional silhouette. Become the BabaYaga." },
            { lvl: 700, title: "Atomic-proof Suit", desc: "Rated for explosions, fallout, and extremely bad decisions." },
            { lvl: 800, title: "Space Suit", desc: "Life support disguised as fashion. Vacuum approved." },
            { lvl: 900, title: "Netherite Armor", desc: "Forged from materials that laugh at lava. Stronger than logic itself. (See: :contentReference[oaicite:0]{index=0})" },
            { lvl: 1000, title: "Morphing Suit", desc: "Adapts to any situation instantly. Identity becomes optional." }
        ]
    },
    {
        id: 9,
        name: "Furniture Dept.",
        icon: "🛋️",
        level: 0,
        baseCost: 100000,
        baseIncome: 1000,
        isUnlocked: false,
        minUnlockBalance: 100000,
        requiredArea: 4,
        milestones: [
            { lvl: 0, title: "Wooden Stool", desc: "Simple, wobbly, and slightly punishing to sit on. Builds character—or back pain." },
            { lvl: 10, title: "Folding Chair", desc: "Portable but slightly uncomfortable. Ideal for awkward family gatherings." },
            { lvl: 20, title: "Dining Table", desc: "Where meals and gossip both reach their peak. Slightly sticky surfaces included." },
            { lvl: 30, title: "Bookshelf", desc: "Holds knowledge and occasionally spiders. The more cluttered, the wiser you feel." },
            { lvl: 40, title: "Armchair", desc: "Comfortable and judgmental. Perfect for reading or plotting." },
            { lvl: 50, title: "Couch", desc: "Seats multiple people and half your problems. Snacks optional." },
            { lvl: 60, title: "Coffee Table", desc: "Holds drinks, magazines, and your life choices. Decorative coaster included." },
            { lvl: 70, title: "Wardrobe", desc: "Holds clothes, secrets, and occasionally Narnia." },
            { lvl: 80, title: "Bed", desc: "Rest, dreams, and awkward morning hair guaranteed." },
            { lvl: 90, title: "Recliner", desc: "Adjusts angles for maximum laziness. Cat optional." },
            { lvl: 100, title: "Ottoman", desc: "Footrest, storage, and weapon in a pinch. Multi-functional genius." },
            { lvl: 125, title: "Gaming Chair", desc: "Ergonomics optimized. Also broadcasts your epic rage to friends." },
            { lvl: 150, title: "Murphy Bed", desc: "Folds into the wall. Small apartments rejoice." },
            { lvl: 175, title: "Floating Shelf", desc: "Invisible supports hold your treasures. Slightly magical." },
            { lvl: 200, title: "Glowing Lamp", desc: "Illuminates rooms and existential crises alike. Slightly enchanted." },
            { lvl: 250, title: "Secret Compartment Desk", desc: "Hide valuables or skeletons. Literally, maybe." },
            { lvl: 300, title: "Hammock", desc: "Suspends you over the ground. Also your dignity if you fall." },
            { lvl: 350, title: "Throne Chair", desc: "Assumes you’re royalty. Acts like it too." },
            { lvl: 400, title: "Bookshelf of Babel", desc: "Reference to . Holds every book imaginable and some that shouldn’t exist." },
            { lvl: 500, title: "End Table of Holding", desc: "Tiny table, infinite storage. Bags appear where physics disagrees." },
            { lvl: 600, title: "Levitation Couch", desc: "Floats gently above the floor. Nap physics slightly violated." },
            { lvl: 700, title: "Time-Chair", desc: "Sitting here briefly slows time. Productivity spikes or fails accordingly." },
            { lvl: 800, title: "Dimensional Bookshelf", desc: "Contains entire worlds in hidden compartments. Occasionally eats your socks." },
            { lvl: 900, title: "Sentient Desk", desc: "Knows what you want before you do. Offers unsolicited advice." },
            { lvl: 1000, title: "Reality Furniture Set", desc: "Every item bends reality slightly. Comfort is optional; existential dread guaranteed." }
        ]
    },
    {
        id: 10,
        name: "Toy Dept.",
        icon: "🧸",
        level: 0,
        baseCost: 180000,
        baseIncome: 2200,
        isUnlocked: false,
        minUnlockBalance: 180000,
        requiredArea: 4,
        milestones: [
            { lvl: 0, title: "Wooden Blocks", desc: "Stack them, knock them down, repeat. Early engineering and minor frustration included." },
            { lvl: 10, title: "Toy Car", desc: "Push it across the floor. Minor racing championships optional." },
            { lvl: 20, title: "Doll", desc: "Plastic friend for imaginative play. May talk back if you listen closely." },
            { lvl: 30, title: "Stuffed Animal", desc: "Soft, cuddly, and judging you silently. Comfort guaranteed." },
            { lvl: 40, title: "Puzzle", desc: "Test your patience. Satisfaction upon completion is scientifically proven." },
            { lvl: 50, title: "Board Game", desc: "Family fun and arguments combined. Monopoly skills recommended." },
            { lvl: 60, title: "Yo-Yo", desc: "Master tricks or face minor string-related injuries." },
            { lvl: 70, title: "Rubik’s Cube", desc: "Colorful confusion. Great for intellectual flexing and finger cramps." },
            { lvl: 80, title: "Remote-Control Car", desc: "Speed, agility, and the joy of causing minor property damage." },
            { lvl: 90, title: "Lego Set", desc: "Creativity unlocked. Pain threshold for stepping on pieces required." },
            { lvl: 100, title: "Nerf Gun", desc: "Foam combat simulator. Accuracy optional, laughter guaranteed." },
            { lvl: 125, title: "Video Game Console", desc: "Pixelated fun. Hours lost, high scores achieved." },
            { lvl: 150, title: "VR Headset", desc: "Step into other worlds. Furniture collisions optional but likely." },
            { lvl: 175, title: "Board Game of Doom", desc: " inspired. Play carefully; chaos guaranteed." },
            { lvl: 200, title: "Magic 8-Ball", desc: "Answers all questions vaguely. Fate is mostly random." },
            { lvl: 250, title: "Talking Doll", desc: "Repeated phrases. Slightly creepy at 3 AM." },
            { lvl: 300, title: "Remote-Control Robot", desc: "Moves, dances, and occasionally misbehaves spectacularly." },
            { lvl: 350, title: "AI Toy Companion", desc: "Learns your preferences. Occasionally judges your life choices." },
            { lvl: 400, title: "Holographic Board Game", desc: " nod. Play in 3D, stakes slightly higher." },
            { lvl: 500, title: "Transforming Mecha", desc: "Toys that turn into vehicles. Childhood dreams realized, furniture may suffer." },
            { lvl: 600, title: "Living Plushie", desc: "Soft, cute, and sentient. Demands snacks and attention." },
            { lvl: 700, title: "Time-Travel Game", desc: "Moves through history and future. Players may end up in the wrong century." },
            { lvl: 900, title: "Multiverse Puzzle", desc: "Each piece exists in a different reality. Completion impossible, fun guaranteed." },
            { lvl: 1200, title: "Reality-Bending Toy Chest", desc: "Pull out anything you can imagine… but sometimes it imagines you first." },
            { lvl: 1500, title: "Toy of Creation", desc: "Build worlds, mini-cities, and miniature universes. Side effects: minor omnipotence." }
        ]
    },
    {
        id: 11,
        name: "Perfume Dept.",
        icon: "🧴",
        level: 0,
        baseCost: 350000,
        baseIncome: 5000,
        isUnlocked: false,
        minUnlockBalance: 350000,
        requiredArea: 5,
        milestones: [
            { lvl: 0, title: "Poop Perfume", desc: "Aggressively unpleasant. Clears rooms instantly and establishes dominance in all social settings." },
            { lvl: 10, title: "Moldy Perfume", desc: "Smells like a forgotten basement. Nostalgic for all the wrong reasons." },
            { lvl: 20, title: "Nothing Perfume", desc: "Absolutely no scent. People assume you’re naturally like this." },
            { lvl: 30, title: "Lightly Flavored Perfume", desc: "A faint hint of something nice. You have to lean in awkwardly to notice." },
            { lvl: 40, title: "Sweet Perfume", desc: "Sugary and pleasant. Bees show mild interest." },
            { lvl: 50, title: "Floral Perfume", desc: "Extracted directly from flowers that worked very hard for this." },
            { lvl: 60, title: "Citrus Perfume", desc: "Sharp, bright, and aggressively awake. Wakes people up emotionally." },
            { lvl: 70, title: "Vanilla Perfume", desc: "Warm and comforting. Smells like trust." },
            { lvl: 80, title: "Ocean Breeze Perfume", desc: "Smells like the sea, minus the fish crimes." },
            { lvl: 90, title: "Luxury Perfume", desc: "Comes in a tiny bottle. Costs more than rent." },
            { lvl: 100, title: "Signature Scent", desc: "People start associating this smell with you permanently." },
            { lvl: 125, title: "Confidence Perfume", desc: "Doesn’t change anything physically. Somehow works anyway." },
            { lvl: 150, title: "Memory Perfume", desc: "Smells like a specific moment you forgot you missed." },
            { lvl: 175, title: "NPC Perfume", desc: "Smells extremely normal. You blend into crowds flawlessly." },
            { lvl: 200, title: "Main Character Cologne", desc: "Everyone notices when you enter a room. Background music implied." },
            { lvl: 250, title: "Forbidden Scent", desc: "Discontinued everywhere for reasons no one will explain." },
            { lvl: 300, title: "Boss Perfume", desc: "Smells expensive, dangerous, and unskippable." },
            { lvl: 350, title: "Stealth Fragrance", desc: "Actively removes your scent. Dogs become confused." },
            { lvl: 400, title: "Time-Locked Perfume", desc: "Smells different depending on the era you’re in." },
            { lvl: 500, title: "Emotion Amplifier", desc: "Whatever you’re feeling, others feel it too." },
            { lvl: 600, title: "Prestige Perfume", desc: "Resets your scent collection but makes every future smell better." },
            { lvl: 700, title: "Quantum Fragrance", desc: "Smells different to each person observing it." },
            { lvl: 800, title: "Divine Aroma", desc: "Said to be worn by gods. Mortals get nosebleeds." },
            { lvl: 900, title: "Cosmic Cologne", desc: "Smells like stars, void, and ambition." },
            { lvl: 1000, title: "Scent of Reality", desc: "This is what existence smells like. You can’t unnotice it." }
        ]
    },
    {
        id: 12,
        name: "Television Dept.",
        icon: "📺",
        level: 0,
        baseCost: 600000,
        baseIncome: 10000,
        isUnlocked: false,
        minUnlockBalance: 600000,
        requiredArea: 5,
        milestones: [
            { lvl: 0, title: "One Pixel", desc: "A single glowing dot. Entertainment is entirely theoretical at this stage." },
            { lvl: 10, title: "100 Years Ago", desc: "Barely moving images flicker on screen. People gather around it anyway." },
            { lvl: 20, title: "Black and White", desc: "No color, but infinite imagination. Cinema purists begin forming opinions." },
            { lvl: 30, title: "Color TV!", desc: "Suddenly everything is vibrant. Nature documentaries become dangerous." },
            { lvl: 40, title: "Bigger", desc: "Same quality, more screen. Everyone stands closer than necessary." },
            { lvl: 50, title: "Thinner", desc: "Defies expectations and gravity. Wall mounting unlocked." },
            { lvl: 60, title: "Better Resolution", desc: "Faces gain pores. Makeup budgets increase." },
            { lvl: 70, title: "High Definition (HD)", desc: "Every detail is visible. You notice things you shouldn’t." },
            { lvl: 80, title: "Ultra High Definition (UHD)", desc: "So sharp it feels personal. Background actors become main characters." },
            { lvl: 90, title: "8K Ultra High Definition (8K UHD)", desc: "Stunning clarity with absolutely no content made for it." },
            { lvl: 100, title: "16K Ultra High Definition (16K UHD)", desc: "You can see individual thoughts forming. Completely unnecessary." },
            { lvl: 125, title: "Speaker Import", desc: "Sound finally matches the visuals. Neighbors take notice." },
            { lvl: 150, title: "Super Flat", desc: "So flat it feels like a portal instead of a screen." },
            { lvl: 175, title: "Triangular Pixels", desc: "Engineers insisted this would be better. They were wrong, but confident." },
            { lvl: 200, title: "Round Pixels", desc: "Nothing is sharp anymore. Everything feels friendly." },
            { lvl: 250, title: "Scent-Streamer", desc: "This screen is actually a specialized air-purifier that releases micro-scents perfectly synced with the content on screen." },
            { lvl: 300, title: "EcoVision", desc: "Runs on plant-based energy and actively cleans the air. The TV judges you for wasting power." },
            { lvl: 350, title: "Camouflage Screen", desc: "Blends perfectly into your wall when off. Guests think you’re lying about owning a TV." },
            { lvl: 400, title: "QuantumVision X9000", desc: "Uses quantum nanotechnology to produce colors so vivid your brain needs recalibration." },
            { lvl: 500, title: "Real World Resolution", desc: "Indistinguishable from reality. Existential questions arise." },
            { lvl: 600, title: "The Narrator", desc: "Doesn't show news or entertainment, but rather, a perfectly curated, live-action documentary of a random person's life somewhere in the world. Narrated by a soothing, omniscient voice." },
            { lvl: 700, title: "HoloScreen 3D", desc: "Projects images directly into your living room. Furniture becomes optional." },
            { lvl: 800, title: "DreamStream TV", desc: "Plays your dreams and imagination. Nightmares are considered premium content." },
            { lvl: 900, title: "SpaceTime TV", desc: "Watch anything from any point in space and time. Spoilers are unavoidable." },
            { lvl: 1000, title: "MultiVerse Viewer", desc: "Streams shows from parallel universes. Some versions are better. Some are cursed." }
        ]
    },
    {
        id: 13,
        name: "Phone Dept.",
        icon: "📱",
        level: 0,
        baseCost: 1000000,
        baseIncome: 25000,
        isUnlocked: false,
        minUnlockBalance: 1000000,
        requiredArea: 6,
        milestones: [
            { lvl: 0, title: "Brick", desc: "Heavy, rectangular, and technically indestructible. Can make calls and double as self-defense." },
            { lvl: 10, title: "Corded Phone", desc: "Tethered to the wall like an obedient appliance. Privacy was never an option." },
            { lvl: 20, title: "Flippy Phone", desc: "Ends every call with dramatic satisfaction. Makes you feel powerful for no reason." },
            { lvl: 30, title: "Nokiaaa", desc: "Legend says it cannot be destroyed. Dropping it damages the floor instead." },
            { lvl: 40, title: "BlackJelly", desc: "Tiny, sleek, and aggressively minimalist. Does less, but somehow costs more." },
            { lvl: 50, title: "Jphone", desc: "Smooth glass slab with exactly one button you’ll never use." },
            { lvl: 60, title: "Jphone Plus", desc: "Bigger screen, heavier regret. You now need two hands and a dream." },
            { lvl: 70, title: "Jphone Upgraded", desc: "Slightly faster, slightly better camera. Looks identical to last year’s model." },
            { lvl: 80, title: "No-Headphone-Jack Phone", desc: "Bravely removed features in the name of courage." },
            { lvl: 90, title: "Foldy Phone", desc: "Bends reality and your trust. Very cool until it isn’t." },
            { lvl: 100, title: "Ultra Camera Phone", desc: "Can photograph the moon, ants, and your mistakes in stunning detail." },
            { lvl: 125, title: "Gamer Phone", desc: "RGB lights included. Battery drains heroically." },
            { lvl: 150, title: "Bezel-less Phone", desc: "All screen, no edges. Accidentally presses itself." },
            { lvl: 175, title: "AI Assistant Phone", desc: "Listens constantly. Claims it’s for your benefit." },
            { lvl: 200, title: "Satellite Phone", desc: "Works anywhere on Earth. Socially isolating but reliable." },
            { lvl: 250, title: "Transparent Phone", desc: "You can see all the parts. Still don’t know how it works." },
            { lvl: 300, title: "Hologram Phone", desc: "Projects calls into the air. Looks amazing in dark rooms." },
            { lvl: 350, title: "Thought-Controlled Phone", desc: "No touch required. Accidentally opens apps when you panic." },
            { lvl: 400, title: "Quantum Phone", desc: "Exists in multiple states. Battery may already be dead." },
            { lvl: 500, title: "Time-Travel Phone", desc: "Can call the past or future. Missed calls become terrifying." },
            { lvl: 600, title: "Multiverse Phone", desc: "Receives notifications from alternate versions of you." },
            { lvl: 700, title: "God Phone", desc: "Omniscient, omnipresent, and still asks for updates." },
            { lvl: 800, title: "Reality Remote", desc: "Not just a phone anymore. Swipe to change existence." },
            { lvl: 900, title: "Morphing Device", desc: "Becomes whatever tech you need. Phone is just a suggestion now." }
        ]
    },
    {
        id: 14,
        name: "Technology Dept.",
        icon: "🌐",
        level: 0,
        baseCost: 2000000,
        baseIncome: 50000,
        isUnlocked: false,
        minUnlockBalance: 2000000,
        requiredArea: 6,
        milestones: [
            { lvl: 0, title: "Wheel", desc: "The first tech breakthrough. People spin it and immediately feel clever." },
            { lvl: 10, title: "Fire", desc: "Heat and light unlocked. Also burns things you didn’t intend." },
            { lvl: 20, title: "Lever", desc: "Lifts objects. Greatly improves laziness efficiency." },
            { lvl: 30, title: "Pulley", desc: "Makes heavy things lighter… sometimes at the cost of physics." },
            { lvl: 40, title: "Printing Press", desc: "Information spreads faster than your social anxiety." },
            { lvl: 50, title: "Steam Engine", desc: "Powers trains, factories, and mild existential dread." },
            { lvl: 60, title: "Telegraph", desc: "Communicate across distances. Morse code enthusiasts rejoice." },
            { lvl: 70, title: "Telephone", desc: "Now people can call you to ruin your day instantly." },
            { lvl: 80, title: "Light Bulb", desc: "Darkness optional. Edison approves, Tesla rolls his eyes." },
            { lvl: 90, title: "Radio", desc: "Music and propaganda, delivered directly to your ear." },
            { lvl: 100, title: "Television", desc: "Moving pictures and drama, but now in your living room." },
            { lvl: 125, title: "Computer", desc: "Calculates faster than you ever could. Also perfect for procrastination." },
            { lvl: 150, title: "Internet", desc: "Global brain unlocked. Memes spread uncontrollably." },
            { lvl: 175, title: "Smartphone", desc: "Everything you need, including distractions you didn’t ask for." },
            { lvl: 200, title: "Wi-Fi", desc: "No wires. Instant connection. Chaos and cat videos everywhere." },
            { lvl: 250, title: "3D Printing", desc: "Objects appear from nothing. Your imagination is now taxable." },
            { lvl: 300, title: "AI Assistant", desc: "Listens constantly. Can remind you of regrets before you even make them." },
            { lvl: 350, title: "Self-Driving Car", desc: "Let a machine stress about traffic instead of you. Accidents still happen." },
            { lvl: 400, title: "Quantum Computer", desc: "Solves problems while simultaneously existing in multiple states. Brain melts optional." },
            { lvl: 500, title: "Teleportation Device", desc: "Instant travel, but slightly disconcerting if you misplace a limb." },
            { lvl: 600, title: "Neural Link", desc: "Connect directly to the cloud. Privacy is a nostalgic concept." },
            { lvl: 700, title: "Nanotechnology", desc: "Tiny machines do everything you can’t see. Chaos guaranteed." },
            { lvl: 8000, title: "Time Manipulator", desc: "Rewind mistakes or skip work entirely. Side effects may include paradoxes." },
            { lvl: 900, title: "Multiverse Terminal", desc: "Access alternate realities. Some of them are broken. Very broken." },
            { lvl: 1000, title: "Reality Compiler", desc: "Rewrites the rules of existence. Your tycoon empire now literally runs the world." }
        ]
    },
    {
        id: 15,
        name: "Jewelry Dept.",
        icon: "💎",
        level: 0,
        baseCost: 3500000,
        baseIncome: 120000,
        isUnlocked: false,
        minUnlockBalance: 3500000,
        requiredArea: 7,
        milestones: [
            { lvl: 0, title: "Plastic Ring", desc: "Cheap, colorful, and mostly sentimental. Slightly sticky if left in the sun." },
            { lvl: 10, title: "Costume Jewelry", desc: "Looks fancy. Lasts a weekend. Imagination provides durability." },
            { lvl: 20, title: "Silver Ring", desc: "Shiny, affordable, and socially acceptable. Slightly tarnishes with stress." },
            { lvl: 30, title: "Gold Necklace", desc: "Immediate wealth signal. Slightly heavier than you expected." },
            { lvl: 40, title: "Pearl Earrings", desc: "Classic, elegant, and occasionally stolen from oysters." },
            { lvl: 50, title: "Diamond Ring", desc: "Sparkles brighter than your ambition. Social status +10." },
            { lvl: 60, title: "Ruby Pendant", desc: "Red, fiery, and slightly intimidating in the right lighting." },
            { lvl: 70, title: "Emerald Bracelet", desc: "Green elegance. Claims to improve your charm stat." },
            { lvl: 80, title: "Sapphire Crown", desc: "Blue stones, heavy dreams. Nobility is implied." },
            { lvl: 90, title: "Amulet of Power", desc: "Not technically magical. Still makes people nervous." },
            { lvl: 100, title: "Choker", desc: "Fashionable restraint. Instantly trendy at parties." },
            { lvl: 125, title: "Brooch", desc: "Pins things together. And maybe reality, if you press hard enough." },
            { lvl: 150, title: "Ring of Invisibility", desc: "Classic nod to . You disappear in style. Side effects vary." },
            { lvl: 175, title: "One Ring Replica", desc: "Even as a fake, it radiates ego. Dangerous to wear casually." },
            { lvl: 200, title: "Heart of the Ocean", desc: "From . Legendary, massive, and very expensive." },
            { lvl: 250, title: "Arkenstone Necklace", desc: "From . Radiates greed and admiration." },
            { lvl: 300, title: "Infinity Gem Earrings", desc: "Snap optional. Reality questionable." },
            { lvl: 350, title: "Cursed Tiara", desc: "Makes everyone look at you. Some consequences are unavoidable." },
            { lvl: 400, title: "Dragon Scale Pendant", desc: "Extremely rare. Slightly warm. Also slightly judgmental." },
            { lvl: 500, title: "Mermaid’s Tear", desc: "Liquid gem encased in crystal. Sells for roughly a city block." },
            { lvl: 600, title: "Phoenix Feather Ring", desc: "Glows faintly. Occasionally bursts into tiny flames." },
            { lvl: 700, title: "Moonstone Circlet", desc: "Shifts color with your mood. Mostly helpful for dramatic entrances." },
            { lvl: 800, title: "Galactic Crown", desc: "Cosmic dust and stars embedded. Ownership may bend spacetime slightly." },
            { lvl: 900, title: "Multiverse Amulet", desc: "Access to jewelry from infinite realities. Some versions are cursed, some sentient." },
            { lvl: 1000, title: "Reality Gem", desc: "Possessing it may rewrite probability itself. Fortune and chaos included." }
        ]
    },
    {
        id: 16,
        name: "Pharmacy Dept.",
        icon: "💊",
        level: 0,
        baseCost: 7000000,
        baseIncome: 250000,
        isUnlocked: false,
        minUnlockBalance: 7000000,
        requiredArea: 7,
        milestones: [
            { lvl: 0, title: "Band-Aids", desc: "Sticky little helpers for tiny injuries. Slightly questionable adhesion." },
            { lvl: 10, title: "Cough Syrup", desc: "Sweet, medicinal, and vaguely effective. Side effects: naps." },
            { lvl: 20, title: "Vitamin C", desc: "Boosts health… or confidence. Your choice." },
            { lvl: 30, title: "Aspirin", desc: "Pain relief in tablet form. Works better with dramatic music." },
            { lvl: 40, title: "Antibiotics", desc: "Kills bacteria efficiently. Misuse may awaken microbiologist rage." },
            { lvl: 50, title: "Antihistamines", desc: "Allergy relief. Sneezing not included." },
            { lvl: 60, title: "Eye Drops", desc: "Clear vision, literally and metaphorically." },
            { lvl: 70, title: "Pain Cream", desc: "Rub on injuries. Also works for emotional pain, maybe." },
            { lvl: 80, title: "Sleep Aid", desc: "Helps you nap anywhere. Productivity may temporarily collapse." },
            { lvl: 90, title: "Energy Drink", desc: "Caffeine-fueled optimism in a can. Heart rate optional." },
            { lvl: 100, title: "Probiotics", desc: "Gut health upgrade. Your stomach will send thank-you emails." },
            { lvl: 125, title: "Prescription Meds", desc: "Strong effects. Side effects include existential dread and insurance paperwork." },
            { lvl: 150, title: "Pain Reliever Shots", desc: "Immediate relief. Slight chance of heroic bravery." },
            { lvl: 175, title: "Herbal Tinctures", desc: "Nature’s magic in bottles. May summon fairies if left in moonlight." },
            { lvl: 200, title: "Flu Vaccine", desc: "Prevents illness and social judgment. Immunity feels expensive." },
            { lvl: 250, title: "Nootropics", desc: "Smart pills. Brain activity increases. Productivity spikes and paranoia follow." },
            { lvl: 300, title: "Elixir of Vitality", desc: "Fantasy-inspired potion. Slightly sparkly. Does what it says on the label." },
            { lvl: 350, title: "Mana Potion", desc: " reference. Restores magical energy. Side effects: overconfidence." },
            { lvl: 400, title: "Invisibility Serum", desc: "You vanish for a short time. Slight chance of fainting or existential crisis." },
            { lvl: 500, title: "Cursed Tonic", desc: "Grants great power… but also slightly regrets your life choices." },
            { lvl: 600, title: "Time Elixir", desc: "Drink to experience seconds slower or faster. Very confusing." },
            { lvl: 700, title: "Universal Antidote", desc: "Neutralizes poisons from every known world. Some unknown worlds remain." },
            { lvl: 800, title: "Alien Serum", desc: "Not intended for humans. Still wildly popular. Glow optional." },
            { lvl: 900, title: "Multiverse Medicine", desc: "Cures or affects beings from infinite realities. Side effects vary drastically." },
            { lvl: 1000, title: "Philosopher’s Elixir", desc: "Legendary potion said to grant immortality, wisdom, and slightly annoying omniscience." }
        ]
    },
    {
        id: 17,
        name: "Optics Dept.",
        icon: "👓",
        level: 0,
        baseCost: 12000000,
        baseIncome: 500000,
        isUnlocked: false,
        minUnlockBalance: 12000000,
        requiredArea: 8,
        milestones: [
            { lvl: 0, title: "Magnifying Glass", desc: "See things bigger. Great for ants, small text, and minor ego boosts." },
            { lvl: 10, title: "Reading Glasses", desc: "Helps read menus, instructions, and conspiracy theories. Fashion optional." },
            { lvl: 20, title: "Binoculars", desc: "Bring distant objects dangerously close. Neighborhood surveillance guaranteed." },
            { lvl: 30, title: "Monocular", desc: "One-eyed vision. Slightly stylish pirate vibes included." },
            { lvl: 40, title: "Sunglasses", desc: "Blocks sun, looks cool. Shades optional, confidence mandatory." },
            { lvl: 50, title: "VR Headset", desc: "Escape reality instantly. Side effect: losing your sense of time." },
            { lvl: 60, title: "AR Glasses", desc: "Overlay the digital world onto the real one. Notifications now haunt your vision." },
            { lvl: 70, title: "Night Vision Goggles", desc: "See in the dark. Crime-fighting or midnight snacking, your choice." },
            { lvl: 80, title: "Laser Glasses", desc: "Stylish and slightly dangerous. Not recommended for pets." },
            { lvl: 90, title: "Smart Glasses", desc: "Answer calls, read messages, and judge your outfit simultaneously." },
            { lvl: 100, title: "Telescope", desc: "Gaze at stars, planets, and distant plot holes in soap operas." },
            { lvl: 125, title: "Periscope", desc: "Look over obstacles. Ideal for submersible furniture spying." },
            { lvl: 150, title: "HoloLens", desc: "Projects holograms directly into your field of vision. Productivity spikes or collapses." },
            { lvl: 175, title: "X-Ray Goggles", desc: "Not FDA-approved. Peek inside walls and sandwiches alike." },
            { lvl: 200, title: "Binocular Contact Lenses", desc: "Magnify the world in your eyeballs. Slight dizziness optional." },
            { lvl: 250, title: "Thermal Vision Goggles", desc: "Detect heat signatures. Ideal for wildlife watching or late-night cooking." },
            { lvl: 300, title: "Quantum Glasses", desc: "See multiple outcomes simultaneously. Your brain might short-circuit." },
            { lvl: 350, title: "Time-Shift Lenses", desc: "View moments from the past or future. Spoilers guaranteed." },
            { lvl: 400, title: "Portal Specs", desc: "Gaze into other dimensions. Physics strongly discouraged." },
            { lvl: 500, title: "Alien Vision Goggles", desc: "Perceive electromagnetic waves unknown to humans. Slight nausea included." },
            { lvl: 600, title: "Omni-Optics", desc: "Everything everywhere. The universe is now your screensaver." },
            { lvl: 700, title: "Multiverse Viewer Glasses", desc: "Peek into infinite realities. Side effects: existential dread." },
            { lvl: 900, title: "Holo-Immersion Visor", desc: "Replaces reality entirely. Furniture is optional, physics optional, sanity optional." },
            { lvl: 1200, title: "Reality-Bending Optics", desc: "See and manipulate reality itself. Owners occasionally become minor gods." },
            { lvl: 1500, title: "Eye of Eternity", desc: "A single glance rewrites probability. Also doubles as a very expensive paperweight." }
        ]
    },
    {
        id: 18,
        name: "Pet Dept.",
        icon: "🐾",
        level: 0,
        baseCost: 20000000,
        baseIncome: 750000,
        isUnlocked: false,
        minUnlockBalance: 20000000,
        requiredArea: 8,
        milestones: [
            { lvl: 0, title: "Goldfish", desc: "Tiny, watery companion. Memorable for its short attention span and constant staring." },
            { lvl: 10, title: "Hamster", desc: "Furry, wheel-running stress ball. Great for procrastination therapy." },
            { lvl: 20, title: "Cat", desc: "Judgmental, independent, and occasionally loving. Ideal for knocking over your coffee." },
            { lvl: 30, title: "Dog", desc: "Loyal, energetic, and moderately trainable. Requires snacks and existential affection." },
            { lvl: 40, title: "Parrot", desc: "Repeats everything. Your secrets are no longer safe." },
            { lvl: 50, title: "Turtle", desc: "Slow and wise. Rarely surprises you, but makes you feel like you’re winning at life." },
            { lvl: 60, title: "Ferret", desc: "Mischief wrapped in fur. Hilarity and minor destruction guaranteed." },
            { lvl: 70, title: "Exotic Bird", desc: "Vivid feathers and impossible calls. Your neighbors may report you." },
            { lvl: 80, title: "Miniature Pig", desc: "Intelligent, adorable, and likely to eat everything you love." },
            { lvl: 90, title: "Rabbit", desc: "Soft, cute, and surprisingly clever. Escape artistry included." },
            { lvl: 100, title: "Mini Dragon Hatchling", desc: "Fantasy unlocked. Breathes tiny fire. Slightly singes furniture." },
            { lvl: 125, title: "Phoenix Chick", desc: "Flaming feathers, regenerates from ashes. Bonus: warm cuddles." },
            { lvl: 150, title: "Kitsune Fox", desc: "Shapeshifting magic fox. Mischief guaranteed, intelligence optional." },
            { lvl: 175, title: "Griffin Cub", desc: "Part lion, part eagle, full chaos. Ideal for air superiority in the backyard." },
            { lvl: 200, title: "Unicorn Foal", desc: "Rainbow hooves and glitter mane. May cause spontaneous joy and envy." },
            { lvl: 250, title: "Alien Companion", desc: "Tentacles, multiple eyes, or none at all. Sentient and slightly sarcastic." },
            { lvl: 300, title: "Miniature Kraken", desc: "Tiny tentacles, full personality. Water bowl required or bathroom accidents inevitable." },
            { lvl: 350, title: "Dragonling", desc: "Grows fast, fiery personality included. Can double as an emergency heater." },
            { lvl: 400, title: "Familiar Cat", desc: " nod. Slightly magical, mostly judgmental." },
            { lvl: 500, title: "Chimera Pup", desc: "Parts from multiple animals combined. Cute, terrifying, and chaotic." },
            { lvl: 600, title: "Time-Traveling Turtle", desc: "Moves slowly but appears everywhere you need it. Paradoxes may occur." },
            { lvl: 700, title: "Multiverse Dragon", desc: "Exists in multiple realities at once. Feeding schedule impossible to track." },
            { lvl: 900, title: "Celestial Owl", desc: "Knows your destiny. May or may not tell you politely." },
            { lvl: 1200, title: "Pocket Black Hole", desc: "Tiny gravity anomaly. Sucks up misbehavior and small furniture." },
            { lvl: 1500, title: "Reality Familiar", desc: "A pet that transcends universes. Love it, fear it, or both. Tycoon empire optional." }
        ]
    },
    {
        id: 19,
        name: "Vehicle Dept.",
        icon: "🚗",
        level: 0,
        baseCost: 35000000,
        baseIncome: 1000000,
        isUnlocked: false,
        minUnlockBalance: 35000000,
        requiredArea: 9,
        milestones: [
            { lvl: 0, title: "Bicycle", desc: "Two wheels, one pedal, and all the effort. Great for cardio, terrible for lazy tycoons." },
            { lvl: 10, title: "Scooter", desc: "Faster than walking, but not by much. Confidence increases marginally." },
            { lvl: 20, title: "Horse", desc: "Classic transportation. Fuel: hay. Side effect: occasional neighing." },
            { lvl: 30, title: "Cart", desc: "Horse-powered efficiency. Good for hauling small fortunes or vegetables." },
            { lvl: 40, title: "Motorbike", desc: "Speed and style. Also windburn and minor existential crises." },
            { lvl: 50, title: "Car", desc: "Four wheels, a seatbelt, and a mild sense of superiority." },
            { lvl: 60, title: "Convertible", desc: "Wind in your hair, minor chance of sunburn. Fame optional." },
            { lvl: 70, title: "Truck", desc: "Haul anything. Tires optional, cargo not optional." },
            { lvl: 80, title: "SUV", desc: "Status symbol, storage unit, mild environmental hazard." },
            { lvl: 90, title: "Sports Car", desc: "Speed, curves, and aggressively overpriced accessories." },
            { lvl: 100, title: "Electric Car", desc: "Silent, efficient, and morally satisfying. Charging drama included." },
            { lvl: 125, title: "Hoverboard", desc: "Levitation for the trendy. Falls are spectacular." },
            { lvl: 150, title: "Jet Ski", desc: "Water mobility unlocked. Makes waves, literally and socially." },
            { lvl: 175, title: "Helicopter", desc: "Fly above traffic. Noise complaints optional but probable." },
            { lvl: 200, title: "Airplane", desc: "Cross continents in hours. Jet lag included." },
            { lvl: 250, title: "Luxury Yacht", desc: "Status on water. Ice cream and champagne sold separately." },
            { lvl: 300, title: "Submarine", desc: "Explore the deep. Fish judging optional." },
            { lvl: 350, title: "Spaceship", desc: "Escape Earth entirely. Zero-G hairdos guaranteed." },
            { lvl: 400, title: "Time Machine Vehicle", desc: "Travel past or future. Parking violations unresolved." },
            { lvl: 500, title: "Hover Car", desc: "Levitate above roads. Traffic jams become optional existential puzzles." },
            { lvl: 600, title: "Flying Fortress", desc: "Carry everything and everyone. Dramatic entrances mandatory." },
            { lvl: 700, title: "TARDIS Replica", desc: "Bigger on the inside. Doors are confusing.  inspired." },
            { lvl: 900, title: "Batmobile Replica", desc: "Gotham-inspired. Turbo and dramatic theme music included." },
            { lvl: 1200, title: "Multiverse Vehicle", desc: "Access alternate realities while driving. Some lanes are optional, some are paradoxical." },
            { lvl: 1500, title: "Reality Cruiser", desc: "Breaks physics. Breaks expectations. Breaks the economy. All in style." }
        ]
    },
    {
        id: 20,
        name: "Real Estate Dept.",
        icon: "🏠",
        level: 0,
        baseCost: 100000000,
        baseIncome: 1500000,
        isUnlocked: false,
        minUnlockBalance: 100000000,
        requiredArea: 9,
        milestones: [
            { lvl: 0, title: "Shack", desc: "Basic shelter. Leaks optional, charm mandatory. First step in your empire." },
            { lvl: 10, title: "Hut", desc: "A slight upgrade. Still rustic, but now you can host guests without embarrassment." },
            { lvl: 20, title: "Cabin", desc: "Cozy, woodsy, and slightly insulated against both weather and social interaction." },
            { lvl: 30, title: "Cottage", desc: "Charming and picturesque. Neighbors now notice you exist." },
            { lvl: 40, title: "Apartment", desc: "Modern convenience, shared walls, and suspicious smells included." },
            { lvl: 50, title: "Townhouse", desc: "Vertically efficient living. Privacy slightly improved." },
            { lvl: 60, title: "Condo", desc: "Stylish, minimal maintenance, with HOA rules that punish laziness." },
            { lvl: 70, title: "Villa", desc: "Luxury unlocked. Pools and fountains optional but expected." },
            { lvl: 80, title: "Mansion", desc: "Excessive space, grandeur guaranteed. Slight chance of getting lost indoors." },
            { lvl: 90, title: "Skyscraper Apartment", desc: "Views are dramatic. Elevator etiquette becomes critical." },
            { lvl: 100, title: "Penthouse", desc: "Status visible from miles away. Private rooftop included." },
            { lvl: 125, title: "Castle", desc: "Moats, turrets, and knights optional. Drama mandatory." },
            { lvl: 150, title: "Floating Island", desc: "No land taxes. Occasional drifting makes neighbors jealous." },
            { lvl: 175, title: "Treehouse", desc: "Elevated living, literal bird neighbors. Strong branches required." },
            { lvl: 200, title: "Underground Bunker", desc: "Safe from disasters, slightly claustrophobic. Emergency snacks included." },
            { lvl: 250, title: "Glass Dome Home", desc: "Panoramic views. Privacy strongly discouraged." },
            { lvl: 300, title: "Smart Home", desc: "Everything automated. Arguments now with AI assistants." },
            { lvl: 350, title: "Hogwarts-esque Castle", desc: " vibes. Moving stairs optional, magic mostly included." },
            { lvl: 400, title: "Spaceship Home", desc: "Live anywhere in the solar system. Zero-G furniture optional." },
            { lvl: 500, title: "Underwater Dome", desc: "Aquatic living. Fish roommates guaranteed. Oxygen provided separately." },
            { lvl: 600, title: "Floating Sky City", desc: "Architecture defies gravity. Commutes are exhilarating." },
            { lvl: 700, title: "Dimension-Warp Estate", desc: "Rooms are bigger inside. Laws of physics are politely ignored." },
            { lvl: 900, title: "Multiverse Mansion", desc: "Each room exists in a different reality. Guests may vanish and reappear." },
            { lvl: 1200, title: "Cosmic Palace", desc: "Stars and planets as decoration. Gravity optional. Economics irrelevant." },
            { lvl: 1500, title: "Reality Tower", desc: "Every floor alters reality slightly. You now literally own existence itself." }
        ]
    }
];